name: base
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - jupyterlab
  - pip: 
      #IDE  
    - jupyter-server-proxy 
    - jupyter-vscode-proxy
    - ollama
    - llama-index
    - duckdb
