name: base
channels: 
  - conda-forge
  - defaults
dependencies:   #via conda
  # Analytics Workspace
  - python=3.12
  - pip
  - jupyterlab
  
  # Core dependencies 
  - pydantic>=2.3.0           # Data validation

  # Database drivers and tools
  - sqlalchemy>=2.0.20        # SQL toolkit and ORM
  - ibis-framework>=10.5.0    # Database abstraction layer
  - psycopg2-binary>=2.9.6    # PostgreSQL driver
  - duckdb>=0.9.2             # DuckDB for embedded OLAP

  # Environment and configuration
  - python-dotenv>=1.0.0      # Environment variable management
  - pyyaml>=6.0.2             # YAML configuration support
  - pydantic-settings>=2.9.1  # Settings management with Pydantic
  
  # Logging and monitoring 
  - loguru>=0.7.0             # Better logging
  - rich>=14.0.0              # Rich text formatting

  # Testing
  - pytest>=7.4.0             # Testing framework
  - pytest-asyncio>=0.21.1    # Async test support
  - pytest-cov>=4.1.0         # Coverage reports

  # Development Tools
  - black>=25.1.0             # Code formatting
  - isort>=5.12.0             # Import sorting
  - pre-commit>=4.2.0         # Pre-commit hooks

  # Documentation
  - mkdocs>=1.6.0             # Documentation generator
  - mkdocs-material>=9.5.0    # Material theme for MkDocs

  # Pip Installations
  - pip: 
    # IDEs
    - jupyter-server-proxy 
    - jupyter-vscode-proxy

    # Core Dependencies
    - mcp>=1.6.0              # Model Context Protocol
    - fastapi>=0.103.1        # API framework
    - uvicorn>=0.23.2         # ASGI server for FastAPI
    - httpx>=0.24.1           # Async HTTP client for API calls

    # A2A Protocol
    - git+https://github.com/djsamseng/A2A@prefixPythonPackage#subdirectory=samples/python

    #Authentication and Security 
    - python-jose[cryptography]>=3.3.0  # JWT token handling 
    - passlib[bcrypt]>=1.7.4            # Password hashing

    # Development Tools
    - ruff>=0.11.6
    
    # LLM Integration 
    - ollama
    - llama-index
    - openai>=1.0.0            # OpenAI API
    
    - git+https://github.com/astral-sh/uv
    

